baseURL = "https://example.com"
title = "SamuelDev's Engineer Blog"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2016-{year} SamuelDev. All Rights Reserved."

# Multilingual mode
# defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
googleAnalytics = "UA-49706427-1"

enableRobotsTXT = true
enableEmoji = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
