baseURL = "https://samueldev.io/"
languageCode = "en-us"
title = "SamuelDev Blog"
theme = "tale"
Copyright = "© SamuelDev 2021"

[params]
description = "My personal blog that I use to write about interesting problems I've solved while coding."
authorlocation = "United States"

githubName = "SamuelDev"
email = "samueldevc@gmail.com"

# googleAnalytics = "UA-49706427-1"

# [utterances]
#   repo = "SamuelDev/samueldev.github.io"
#   #issueTerm = "pathname" # pathname, url, title, og:title
#   label = "comment"
#   theme = "preferred-color-scheme" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.